# Generated by Django 5.2.17 on 2026-09-21 16:47

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import identity.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=255, verbose_name='الاسم المعروض')),
                ('active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'شخص',
                'verbose_name_plural': 'الأشخاص',
                'ordering': ('display_name',),
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_platform_admin', models.BooleanField(default=False, help_text='سلطة إدارية داخل التطبيق؛ لا تمنح تأليفًا مهنيًا.', verbose_name='مدير المنصة')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='identity.person', verbose_name='الشخص')),
            ],
            options={
                'verbose_name': 'حساب',
                'verbose_name_plural': 'الحسابات',
            },
            managers=[
                ('objects', identity.models.AccountManager()),
            ],
        ),
        migrations.CreateModel(
            name='CapabilityGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capability_code', models.CharField(max_length=100, verbose_name='رمز الصلاحية')),
                ('scope_kind', models.CharField(choices=[('OWN', 'خاص (OWN)'), ('ALL', 'عام (ALL)')], default='OWN', max_length=8, verbose_name='نطاق الصلاحية')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='صالحة من')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='صالحة إلى')),
                ('delegable', models.BooleanField(default=False, verbose_name='قابلة للتفويض')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الإلغاء')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='capability_grants', to=settings.AUTH_USER_MODEL, verbose_name='الحساب')),
                ('granted_by_account', models.ForeignKey(help_text='الحساب الذي أصدر المنحة. مطلوب دائمًا: الفاعل يبقى معروفًا.', on_delete=django.db.models.deletion.PROTECT, related_name='grants_issued', to=settings.AUTH_USER_MODEL, verbose_name='مُنحت بواسطة')),
            ],
            options={
                'verbose_name': 'منحة صلاحية',
                'verbose_name_plural': 'منح الصلاحيات',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['account', 'capability_code'], name='grant_account_cap_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('valid_from__isnull', True), ('valid_until__isnull', True), ('valid_until__gte', models.F('valid_from')), _connector='OR'), name='grant_validity_window_ordered')],
            },
        ),
    ]
