# Generated by Django 5.2.17 on 2026-09-22 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('identity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='اسم المؤسسة')),
                ('lifecycle', models.CharField(choices=[('LOCAL_ACTIVE', 'نشطة محليًا'), ('ARCHIVED', 'مؤرشفة')], default='LOCAL_ACTIVE', max_length=20, verbose_name='الحالة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الأرشفة')),
                ('created_by_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='institutions_created', to='identity.person', verbose_name='أنشئت بواسطة')),
                ('local_owner_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='local_institutions', to='identity.person', verbose_name='المالك المحلي')),
            ],
            options={
                'verbose_name': 'مؤسسة',
                'verbose_name_plural': 'المؤسسات',
                'ordering': ('name',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('archived_at__isnull', True), ('lifecycle', 'LOCAL_ACTIVE')), models.Q(('archived_at__isnull', False), ('lifecycle', 'ARCHIVED')), _connector='OR'), name='institution_lifecycle_archive_consistent')],
            },
        ),
    ]
